---

- name: Add Elasticsearch 6.x repository
  yum_repository:
    name: elastic-6.x  
    description: elastic repo
    file: logstash
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
