- src: https://github.com/nginxinc/ansible-role-nginx
  name: nginxinc.nginx
  
- src: https://github.com/geerlingguy/ansible-role-memcached.git
  name: memcached
  
- src: https://github.com/enix/ansible-mongodb.git
  name: mongodb
  
- src: https://github.com/UnderGreen/ansible-role-mongodb.git
  name: mongo
  
- src: https://github.com/geerlingguy/ansible-role-nodejs.git
  name: nodejs
