---
- name: Include pre packages
  import_tasks: pre.yml
- name: Add elasticsearch repo
  import_tasks: repo.yml
- name: Install latest 6.x elasticsearch
  yum:
    name: elasticsearch
    state: latest
  notify: Restart ELASTIC
