---
- name: Include pre packages
  import_tasks: pre.yml
- name: Add logstash repo
  import_tasks: repo.yml
- name: Install latest 6.x logstash
  yum:
    name: logstash
    state: latest
  notify: Enable LOGSTASH
- name: Copy logstash configuration files
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root
    group=root
    mode=0644
  with_items:
    - { src: 'input.conf.j2', dest: '{{_config_input}}' }
    - { src: 'output.conf.j2', dest: '{{_config_output}}' }
  notify: Restart LOGSTASH
