---
- name: Include pre packages
  import_tasks: pre.yml
- name: Add elasticsearch repo
  import_tasks: repo.yml
- name: Install latest 6.x kibana
  yum:
    name: kibana
    state: latest
  notify: Restart KIBANA
- name: Install NGINX
  import_tasks: nginx.yml
