---
- name: Update all packages on the system except the kernel
  yum:
    name: '*'
    state: latest
    exclude: kernel

- name: Install epel-release
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- name: Install remi-release
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm 

- name: Install yum-utils
  yum:
    name: yum-utils
