- hosts: all
  vars:
    nodejs_version: "12.x"
    nodejs_install_npm_user: "{{ ansible_user | default(ansible_user_id) }}"
    npm_config_prefix: "/usr/local/lib/npm"
    npm_config_unsafe_perm: "true"
 
  roles:
  - nodejs
